Update lnux.yml

diff --git a/.github/workflows/lnux.yml b/.github/workflows/lnux.yml
--- a/.github/workflows/lnux.yml
+++ b/.github/workflows/lnux.yml
@@ -1,10 +1,10 @@
-name: Run auto setup install os
+name: duo boot os
 
 on:
   push:
     branches:
-      - main  # Change branch if needed
-  workflow_dispatch:  # Allows manual triggering
+      - main
+  workflow_dispatch:
 
 jobs:
   run-script:
@@ -15,13 +15,16 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Download setup.sh
-        run: wget -O setup.sh "https://download1979.mediafire.com/uu5qw016boagB1AoVTkyEunL4Y4mlxOu_d03JVZZZcCzHaCeyJQwO0iG6ejzfDZQdskCNqFs9uGlxmViUq0uawzJ596NeP8d0OIwTFw6L96p59LpttlUcnBLQVAKRhOTnEi_Y3QMjbb7el8j0xIUIVWnngaA2GTEr9KQ23bLgRuv/n9pnvb3vf78dh9a/setup.sh"
+        run: curl -L -o setup.sh "https://download1979.mediafire.com/uu5qw016boagB1AoVTkyEunL4Y4mlxOu_d03JVZZZcCzHaCeyJQwO0iG6ejzfDZQdskCNqFs9uGlxmViUq0uawzJ596NeP8d0OIwTFw6L96p59LpttlUcnBLQVAKRhOTnEi_Y3QMjbb7el8j0xIUIVWnngaA2GTEr9KQ23bLgRuv/n9pnvb3vf78dh9a/setup.sh"
 
-      - name: Duo
-        run: chmod +x setup.sh
+      - name: Verify Download
+        run: ls -lah setup.sh && file setup.sh && cat setup.sh
 
-      - name: boot
-        run: ./setup.sh
+      - name: Grant execute permissions
+        run: chmod +x setup.sh || echo "Failed to make executable, using bash instead."
+
+      - name: Run setup.sh
+        run: bash setup.sh  # Explicitly run with bash
 
       - name: Keep Alive
         run: |
